services:
  - type: web
    name: forecastapp
    buildCommand: dotnet publish -c Release -o out
    staticPublishPath: out/wwwroot
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
